### ISSUE TITLE
Link's Awakening editors?

### ISSUE THREAD

**Issue by Hectate** [Drenn1/ZOSE#1]
Hey @Drenn1 sorry to bring this into your Issues but I wasn't sure how else to reach out. I've been researching editors and ROM information for Link's Awakening DX and it's clear that you have some connection to the authors of the precursors of your work. Specifically, I was able to find and use ZLADE and LALE which are apparently somewhat related to ZOSE/ZOLE. I note that your repositories even mention Lin20 as a credited name.

I'm hoping to build a randomizer for Link's Awakening, similar to the one's done for Zelda 1 and Link to the Past. One of my challenges is understanding how the ROM is laid out and what points to edit to accomplish this goal. Given that there's a body of people that have worked on Link's Awakening editors, it seems to me that there might be information I could get to assist if I could get in touch with the right people or get source to these editors (with permission, obviously). I'm all for doing my own work, and have already started digging using what I can get out of ZLADE/LALE in conjunction with a debugging emulator (bgb) and Google searches for public data (very helpful so far!), but there's no reason to make my life harder than necessary if I can ask a few questions of someone that has been there.

Any recommendations? Got any hot tips for me?

**Comment by Stewmath** [comment]
Not a problem. I'm somewhat in contact with Lin. He's been very willing to share his sources, so you might have luck getting access to ZLADE. Fatories was the writer of LALE, but as far as I remember, I've only interacted with him through youtube comments.

They both have youtube channels, so you could try contacting them through there. I'll ask Lin myself.

**Comment by Hectate** [comment]
Thanks, I appreciate it! I'd left a YT comment for Fatories and someone else (maybe Lin) after finding the videos related to the editors. I actually just now found Lin based on his Github handle (through your repos) and followed that around the web to Twitter where I tweeted at him; assuming I got the right one. Again, thanks!
